# Repository
repo_name: gl-inet/docs4.x
repo_url: https://github.com/gl-inet/docs4.x
edit_uri: ""

site_name: GL.iNet Router Docs 4
site_description: Documentation for GL.iNet Router Productions
site_author: GL.iNet
site_url: https://docs.gl-inet.com/router/en/4/
site_dir: /home/ubuntu/docs-build/router/en/4/
copyright: Copyright &copy; 2023 GL Technologies & Microuter Technologies

theme: 
  name: material
  logo: images/logo_white.svg
  custom_dir: overrides
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - toc.integrate
  # palette:
  #   - scheme: default
  #     primary: white
  #     accent: indigo
  #     toggle:
  #       icon: material/toggle-switch-off-outline
  #       name: Switch to dark mode
  #   - scheme: slate
  #     primary: cyan
  #     accent: cyan
  #     toggle:
  #       icon: material/toggle-switch
  #       name: Switch to light mode
  favicon: images/favicon.png

# Plugins
plugins:
  - search

# Customization
extra:
  analytics:
    provider: google
    property: G-CB08JFHVHT
  social:
    - icon: fontawesome/solid/globe
      link: https://www.gl-inet.com
    - icon: fontawesome/brands/github
      link: https://github.com/gl-inet/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/gl.inet.wifi/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/GLiNetWiFi
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/gl-inet.com/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCBfNEzurltlIeFFCbUgHQyg
    - icon: fontawesome/brands/pinterest
      link: https://www.pinterest.com/glinetWiFi/
  version:
    provider: mike

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe.min.css
  - https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/default-skin/default-skin.min.css
  # we can use the cdn or files
  # - stylesheets/photoswipe.min.css
  # - stylesheets/default-skin.min.css
  - stylesheets/extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe-ui-default.min.js
  # we can use the cdn or files
  # - javascripts/photoswipe.min.js
  # - javascripts/photoswipe-ui-default.min.js
  - javascripts/extra.js

markdown_extensions:
  - attr_list
  - pymdownx.tabbed
  - toc:
      permalink: true
  - pymdownx.details

nav:
  - Home: index.md
  - User Guide:
    - Overview: user_guide/index.md
    - GL-X3000 (Spitz AX):
      - Hardware Info: user_guide/gl-x3000/hardware_info.md
      - First Time Setup: user_guide/gl-x3000/first_time_setup.md
      - Internet: user_guide/gl-x3000/internet.md
      - Wireless: user_guide/gl-x3000/wireless.md
      - Clients: user_guide/gl-x3000/clients.md
      - VPN: user_guide/gl-x3000/vpn.md
      - Applications: user_guide/gl-x3000/applications.md
      - Network: user_guide/gl-x3000/network.md
      - System: user_guide/gl-x3000/system.md
    - GL-MT3000 (Beryl AX):
      - Hardware Info: user_guide/gl-mt3000/hardware_info.md
      - First Time Setup: user_guide/gl-mt3000/first_time_setup.md
      - Internet: user_guide/gl-mt3000/internet.md
      - Wireless: user_guide/gl-mt3000/wireless.md
      - Clients: user_guide/gl-mt3000/clients.md
      - VPN: user_guide/gl-mt3000/vpn.md
      - Applications: user_guide/gl-mt3000/applications.md
      - Network: user_guide/gl-mt3000/network.md
      - System: user_guide/gl-mt3000/system.md
    - GL-AXT1800 (Slate AX):
      - Hardware Info: user_guide/gl-axt1800/hardware_info.md
      - First Time Setup: user_guide/gl-axt1800/first_time_setup.md
      - Internet: user_guide/gl-axt1800/internet.md
      - Wireless: user_guide/gl-axt1800/wireless.md
      - Clients: user_guide/gl-axt1800/clients.md
      - VPN: user_guide/gl-axt1800/vpn.md
      - Applications: user_guide/gl-axt1800/applications.md
      - Network: user_guide/gl-axt1800/network.md
      - System: user_guide/gl-axt1800/system.md
    - GL-A1300 (Slate Plus):
      - Hardware Info: user_guide/gl-a1300/hardware_info.md
      - First Time Setup: user_guide/gl-a1300/first_time_setup.md
      - Internet: user_guide/gl-a1300/internet.md
      - Wireless: user_guide/gl-a1300/wireless.md
      - Clients: user_guide/gl-a1300/clients.md
      - VPN: user_guide/gl-a1300/vpn.md
      - Applications: user_guide/gl-a1300/applications.md
      - Network: user_guide/gl-a1300/network.md
      - System: user_guide/gl-a1300/system.md
    - GL-AX1800 (Flint):
      - Hardware Info: user_guide/gl-ax1800/hardware_info.md
      - First Time Setup: user_guide/gl-ax1800/first_time_setup.md
      - Internet: user_guide/gl-ax1800/internet.md
      - Wireless: user_guide/gl-ax1800/wireless.md
      - Clients: user_guide/gl-ax1800/clients.md
      - VPN: user_guide/gl-ax1800/vpn.md
      - Applications: user_guide/gl-ax1800/applications.md
      - Network: user_guide/gl-ax1800/network.md
      - System: user_guide/gl-ax1800/system.md
    - GL-MT2500/GL-MT2500A (Brume 2):
      - Hardware Info: user_guide/gl-mt2500/hardware_info.md
      - First Time Setup: user_guide/gl-mt2500/first_time_setup.md
      - Internet: user_guide/gl-mt2500/internet.md
      - Clients: user_guide/gl-mt2500/clients.md
      - VPN: user_guide/gl-mt2500/vpn.md
      - Applications: user_guide/gl-mt2500/applications.md
      - Network: user_guide/gl-mt2500/network.md
      - System: user_guide/gl-mt2500/system.md
    - GL-SFT1200 (Opal):
      - Hardware Info: user_guide/gl-sft1200/hardware_info.md
      - First Time Setup: user_guide/gl-sft1200/first_time_setup.md
      - Internet: user_guide/gl-sft1200/internet.md
      - Wireless: user_guide/gl-sft1200/wireless.md
      - Clients: user_guide/gl-sft1200/clients.md
      - VPN: user_guide/gl-sft1200/vpn.md
      - Applications: user_guide/gl-sft1200/applications.md
      - Network: user_guide/gl-sft1200/network.md
      - System: user_guide/gl-sft1200/system.md
    - GL-M2:
      - Hardware Info: user_guide/gl-m2/hardware_info.md
      - First Time Setup: user_guide/gl-m2/first_time_setup.md
    - GL-S200:
      - Hardware Info: user_guide/gl-s200/hardware_info.md
      - First Time Setup: user_guide/gl-s200/first_time_setup.md
      - Internet: user_guide/gl-s200/internet.md
      - Wireless: user_guide/gl-s200/wireless.md
      - Clients: user_guide/gl-s200/clients.md
      - Thread Mesh: user_guide/gl-s200/thread_mesh.md
      - GL Dev Board: user_guide/gl-s200/gl_dev_board.md
      - Bluetooth: user_guide/gl-s200/bluetooth.md
      - VPN: user_guide/gl-s200/vpn.md
      - Applications: user_guide/gl-s200/applications.md
      - Network: user_guide/gl-s200/network.md
      - System: user_guide/gl-s200/system.md
    - GL-S10:
      - Hardware Info: user_guide/gl-s10/hardware_info.md
      - First Time Setup: user_guide/gl-s10/first_time_setup.md
      - User Manual: user_guide/gl-s10/user_manual.md
      - Firmware Compilation Guide: user_guide/gl-s10/firmware_compilation_guide.md
    - GL-MT1300 (Beryl):
      - Hardware Info: user_guide/gl-mt1300/hardware_info.md
      - First Time Setup: user_guide/gl-mt1300/first_time_setup.md
      - Internet: user_guide/gl-mt1300/internet.md
      - Wireless: user_guide/gl-mt1300/wireless.md
      - Clients: user_guide/gl-mt1300/clients.md
      - VPN: user_guide/gl-mt1300/vpn.md
      - Applications: user_guide/gl-mt1300/applications.md
      - Network: user_guide/gl-mt1300/network.md
      - System: user_guide/gl-mt1300/system.md
    - GL-AP1300 (Cirrus):
      - Hardware Info: user_guide/gl-ap1300/hardware_info.md
      - First Time Setup: user_guide/gl-ap1300/first_time_setup.md
      - Internet: user_guide/gl-ap1300/internet.md
      - Wireless: user_guide/gl-ap1300/wireless.md
      - Clients: user_guide/gl-ap1300/clients.md
      - VPN: user_guide/gl-ap1300/vpn.md
      - Applications: user_guide/gl-ap1300/applications.md
      - Network: user_guide/gl-ap1300/network.md
      - System: user_guide/gl-ap1300/system.md
    - GL-X750 (Spitz):
      - Hardware Info: user_guide/gl-x750/hardware_info.md
      - First Time Setup: user_guide/gl-x750/first_time_setup.md
      - Internet: user_guide/gl-x750/internet.md
      - Wireless: user_guide/gl-x750/wireless.md
      - Clients: user_guide/gl-x750/clients.md
      - VPN: user_guide/gl-x750/vpn.md
      - Applications: user_guide/gl-x750/applications.md
      - Network: user_guide/gl-x750/network.md
      - System: user_guide/gl-x750/system.md
    - GL-XE300 (Puli):
      - Hardware Info: user_guide/gl-xe300/hardware_info.md
      - First Time Setup: user_guide/gl-xe300/first_time_setup.md
      - Internet: user_guide/gl-xe300/internet.md
      - Wireless: user_guide/gl-xe300/wireless.md
      - Clients: user_guide/gl-xe300/clients.md
      - VPN: user_guide/gl-xe300/vpn.md
      - Applications: user_guide/gl-xe300/applications.md
      - Network: user_guide/gl-xe300/network.md
      - System: user_guide/gl-xe300/system.md
    - GL-X300B (Collie):
      - Hardware Info: user_guide/gl-x300b/hardware_info.md
      - First Time Setup: user_guide/gl-x300b/first_time_setup.md
      - Internet: user_guide/gl-x300b/internet.md
      - Wireless: user_guide/gl-x300b/wireless.md
      - Clients: user_guide/gl-x300b/clients.md
      - VPN: user_guide/gl-x300b/vpn.md
      - Applications: user_guide/gl-x300b/applications.md
      - Network: user_guide/gl-x300b/network.md
      - System: user_guide/gl-x300b/system.md
    - GL-AR750S (Slate):
      - Hardware Info: user_guide/gl-ar750s/hardware_info.md
      - First Time Setup: user_guide/gl-ar750s/first_time_setup.md
      - Internet: user_guide/gl-ar750s/internet.md
      - Wireless: user_guide/gl-ar750s/wireless.md
      - Clients: user_guide/gl-ar750s/clients.md
      - VPN: user_guide/gl-ar750s/vpn.md
      - Applications: user_guide/gl-ar750s/applications.md
      - Network: user_guide/gl-ar750s/network.md
      - System: user_guide/gl-ar750s/system.md
    - GL-B1300 (Convexa-B):
      - Hardware Info: user_guide/gl-b1300/hardware_info.md
      - First Time Setup: user_guide/gl-b1300/first_time_setup.md
      - Internet: user_guide/gl-b1300/internet.md
      - Wireless: user_guide/gl-b1300/wireless.md
      - Clients: user_guide/gl-b1300/clients.md
      - VPN: user_guide/gl-b1300/vpn.md
      - Applications: user_guide/gl-b1300/applications.md
      - Network: user_guide/gl-b1300/network.md
      - System: user_guide/gl-b1300/system.md
    - GL-S1300 (Convexa-S):
      - Hardware Info: user_guide/gl-s1300/hardware_info.md
      - First Time Setup: user_guide/gl-s1300/first_time_setup.md
      - Internet: user_guide/gl-s1300/internet.md
      - Wireless: user_guide/gl-s1300/wireless.md
      - Clients: user_guide/gl-s1300/clients.md
      - VPN: user_guide/gl-s1300/vpn.md
      - Applications: user_guide/gl-s1300/applications.md
      - Network: user_guide/gl-s1300/network.md
      - System: user_guide/gl-s1300/system.md
    - GL-MV1000 (Brume):
      - Hardware Info: user_guide/gl-mv1000/hardware_info.md
      - First Time Setup: user_guide/gl-mv1000/first_time_setup.md
      - Internet: user_guide/gl-mv1000/internet.md
      - Clients: user_guide/gl-mv1000/clients.md
      - VPN: user_guide/gl-mv1000/vpn.md
      - Applications: user_guide/gl-mv1000/applications.md
      - Network: user_guide/gl-mv1000/network.md
      - System: user_guide/gl-mv1000/system.md
  - FAQ:
    - Overview: faq/index.md
    - Common:
      - First Time Setup: faq/first_time_setup.md
      - Can't access web Admin Panel: faq/cannot_access_web_admin_panel.md
      - Device id, MAC, SN: faq/where_to_find_the_device_id_mac_sn.md
      - Download Firmware: faq/where_to_download_firmware.md
      - What is LuCI: faq/what_is_luci.md
      - Change WAN to LAN: faq/change_wan_to_lan.md
      - Debrick via Uboot: faq/debrick.md
      - LED Indication: faq/led.md
      - Mobile App: faq/mobile_app.md
      - Repair or Reset: faq/repair_network_or_reset_firmware.md
    - Internet:
      - iPhone Tethering Fail: faq/iphone_tethering_fail.md
      - Connect to a Hotspot with a Captive Portal: faq/connect_to_a_hotspot_with_captive_portal.md
      - Produce a Wired Connection: faq/produce_a_wired_connection.md
    - Upgrade:
      - Upgrade to Firmware 4.x: faq/upgrade_to_4.md
      - Upgrade GL-AX1800 to Firmware 4.x: faq/gl-ax1800_upgrade_to_4.md
    - VPN:
      - TCP or UDP: faq/openvpn_tcp_udp.md
      - Block No-VPN Traffic: faq/block_no_vpn_traffic.md
  - Tutorials:
    - Overview: tutorials/index.md
    - Remote Access Web Admin Panel: tutorials/remote_access_web_admin_panel.md
    - Remote SSH to Router: tutorials/remote_ssh_to_router.md
    - Check IP Address: tutorials/how_to_check_if_isp_assigns_you_a_public_ip_address.md
    - Cellular:
      - Upgrade Quectel Module Software: tutorials\upgrade_quectel_module_software.md
      - SMS Forwarding: tutorials/sms_forwarding.md
      - Get Moduel Logs: tutorials/get_module_logs.md
    - VPN:
      - VPN Cascading: tutorials/vpn_cascading.md
      - Accessing client LAN from Server(WireGuard): tutorials\wireguard_server_access_to_client_lan_side.md
  - Interface Guide:
    - Overview: interface_guide/index.md
    - Internet Connection:
      - Internet: interface_guide/internet.md
      - Ethernet: interface_guide/internet_ethernet.md
      - Repeater: interface_guide/internet_repeater.md
      - Tethering: interface_guide/internet_tethering.md
      - Cellular: interface_guide/internet_cellular.md
      - SMS: interface_guide/sms.md
    - Wireless:
      - Wireless: interface_guide/wireless.md
    - Clients:
      - Clients: interface_guide/clients.md
    - VPN:
      - VPN Dashboard: interface_guide/vpn_dashboard.md
      - OpenVPN Client: interface_guide/openvpn_client.md
      - OpenVPN Server: interface_guide/openvpn_server.md
      - WireGuard Client: interface_guide/wireguard_client.md
      - WireGuard Server: interface_guide/wireguard_server.md
      - Tor: interface_guide/tor.md
    - Applications:
      - Plug-ins: interface_guide/plugins.md
      - Dynamic DNS: interface_guide/ddns.md
      - GoodCloud: interface_guide/cloud.md
      - Network Storage: interface_guide/network_storage.md
      - AdGuard Home: interface_guide/adguardhome.md
      - Parental Control: interface_guide/parental_control.md
      - ZeroTier: interface_guide/zerotier.md
      - Tailscale: interface_guide/tailscale.md
    - Network:
      - Firewall: interface_guide/firewall.md
      - Multi-WAN: interface_guide/multi-wan.md
      - LAN: interface_guide/lan.md
      - DNS: interface_guide/dns.md
      - Network Mode: interface_guide/network_mode.md
      - IPv6: interface_guide/ipv6.md
      - MAC Address: interface_guide/mac_address.md
      - Drop-in Gateway: interface_guide/drop-in_gateway.md
      - IGMP Snooping: interface_guide/igmp_snooping.md
      - Hardware Acceleration: interface_guide/hardware_acceleration.md
      - Network Acceleration: interface_guide/network_acceleration.md
    - System:
      - Overview: interface_guide/system_overview.md
      - Firmware Upgrade: interface_guide/firmware_upgrade.md
      - Scheduled Tasks: interface_guide/scheduled_tasks.md
      - Admin Password: interface_guide/admin_password.md
      - Time Zone: interface_guide/time_zone.md
      - Toggle Button Settings: interface_guide/toggle_button_settings.md
      - Log: interface_guide/log.md
      - Reset Firmware: interface_guide/reset_firmware.md
      - Advanced Settings: interface_guide/advanced_settings.md
  - Video Library:
    - Overview: video_library/index.md
  - Community:
    - Overview: community/index.md